#####################################
##########  INPUT SWITCH  ###########
#####################################
input_boolean:
  livingroomfanpower:
    name: PowerToggle
#    initial: off
    icon: mdi:power
  livingroomfannightmode:
    name: Night Mode
#    initial: off
    icon: mdi:weather-night
  livingroomfanoscillate:
    name: Oscillate
#    initial: off
    icon: mdi:code-tags
  abkuhlen:
    name: Abkühlen
    icon: mdi:snowflake
  stopwatch:
    name: Stopwatch
#    initial: off
  dummy:
    name: Dummy
#    initial: off
#####################################
#######  TIMER / STOPWATCH  #########
#####################################    
sensor:    
  - platform: template
    sensors:
      stopwatch:
        friendly_name: "Stopwatch"
        value_template: >
          {% if is_state('input_boolean.stopwatch', 'on') %}
            {{ (now() - states.automation.stopwatch_start.attributes.last_triggered).total_seconds() | int }}
          {%-elif is_state('sensor.stopwatch', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.stopwatch.state }}
          {% endif %}
        unit_of_measurement: 'sec'
        entity_id:
          - automation.stopwatch_start
          - automation.stopwatch_update
          - automation.stopwatch_stop
  - platform: template
    sensors:
      timedyson:
        friendly_name: "Time Left"
        value_template: '{{ (states.input_number.livingroom_fantime.state | int - states.sensor.stopwatch.state | int / 60)| round }}'
        unit_of_measurement: 'min'
#####################################
#########  INPUT SLIDER   ###########
#####################################
input_number:
  livingroom_fanspeed:
    name: Speed
#    initial: 0
    min: 1
    max: 10
    step: 1
    icon: mdi:fan
  livingroom_fantime:
    name: Timer
#    initial: 0
    min: 0
    max: 90
    step: 5
    icon: mdi:timer