binary_sensor:
####################### FLOORPLAN  ##################################################

  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan
    
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Vacuum Room